### ISSUE TITLE
Chunks fail to load.

### ISSUE THREAD

**Issue by ryandw11** [kakaragame/Kakara#101]
**Describe the bug**
No chunks load when starting the game.

**To Reproduce**
1. Use the latest build of the Launcher, Client, and KVanilla and a fresh install (no save data or anything).
2. Launch the game with the launcher.
3. Press the play button.

**Expected behavior**
Chunks should be loading.

**Screenshots**
![image](https://user-images.githubusercontent.com/6239385/106653083-94ea3500-6553-11eb-9c89-23c00be0b956.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Kakara Version: Latest master branch build.

** Additional Information **
Engine test works perfectly and the code has not changed.

**Comment by wherkamp** [comment]
I have the same issue on my laptop.
But I got some new info. The chunks are loading and being generated by Kvanilla properly.

This leaves them to not being rendered.

**Comment by wherkamp** [comment]
Please retry against https://github.com/kakaragame/Kakara/commit/2dcc110777e09db2dc14020445a672cf62067fec
