### ISSUE TITLE
[WIP] Playability Work

### ISSUE THREAD

**Issue by ryandw11** [kakaragame/Kakara#51]
***Things to Implement:***
- [x] Implement item drops when a block breaks.
- [x] Implement picking up items.
- [x] Display item stack amount on HUD.
- [x] Implement Loading Screen
- [x] Outline of the block the player is looking at [See engine issue](https://github.com/kakaragame/Engine/issues/14)
- [X] Implement hardness.
- [X] Make chunks gen faster / better.
- [x] Add a bottom of the world [See KVanilla issue](https://github.com/kakaragame/KVanilla/issues/8)

One thing we need to keep in mind is how we are going to mesh the Core Inventory API with the Engine HUD API. Otherwise known as, how will mods create custom inventories/work spaces.

**Comment by wherkamp** [comment]
Hardness is halfway done. We do need to come up with a algorithm to decide the amount of time. We will also need to change where its located so faster pc's don't break blocks faster.

**Comment by wherkamp** [comment]
The inventory is ready for picking up items.

**Comment by wherkamp** [comment]
Loading screen needs to be designed but, It is being used.

**Comment by ryandw11** [comment]
> Loading screen needs to be designed but, It is being used.

Is there a way we can get percentages for the stages that way it can be displayed?

**Comment by wherkamp** [comment]
> > Loading screen needs to be designed but, It is being used.
> 
> Is there a way we can get percentages for the stages that way it can be displayed?

Yes, I can add that in.

**Comment by wherkamp** [comment]
Completed.
