### ISSUE TITLE
JVM Crash

### ISSUE THREAD

**Issue by ryandw11** [kakaragame/Kakara#90]
**Describe the bug**
JVM crash after loading into single player.

**To Reproduce**
This is computer specific. Unknown what the specific issue is.

**Expected behavior**

**Desktop (please complete the following information):**
 - Windows 10
 - Nvida GTX 3080 (latest driver)
 - AMD Ryzen 7 3700 CPU
  
 Error:
[hs_err_pid22104.log](https://github.com/kakaragame/Kakara/files/5832093/hs_err_pid22104.log)

**Comment by wherkamp** [comment]
TBH. I have no idea.

It will be fixed. However, not now.

**Comment by wherkamp** [comment]
Same error on a 1650.

Full PC specs
Windows 10 Home build 1909
I5-10300H
Nvidia 1650 Driver 442.23

**Comment by wherkamp** [comment]
Error caused when block selector is added.

https://github.com/kakaragame/Kakara/blob/master/client/src/main/java/org/kakara/client/scenes/maingamescene/MainGameScene.java#L175-L180

**Comment by ryandw11** [comment]
Patched in Kakara Engine master build 30. https://github.com/kakaragame/Engine/commit/e515b18c0c83084562879c2f282734508c2b9088
   
Note: A side effect of the patch is that rendering normal meshes are less efficient.
